default_version_endpoint: "app/version"

log:
  dir: ""

allowed_users:
  - kvendingoldo
  - nikolai_mishin
  - yakovenko_sv
  - pangurbano
  - TurangaLipina
  - amenshchikov
  - eramonstera
  - bulgkate
  - chelseadagger
  - satamas
  - mariia_lobanova
  - dkramorov
  - Roman_Verkhovkii

clients:
  - name: ночлежка тест
    type: вк mcs0712976052
    url: mks.homeless.ru

  - name: БФ "Ковчег"
    type: вк mcs8866994743
    url: mks.ossne.ru

  - name: БФ "Люблю и благодарю"
    type: вк mcs4786614812
    url: mks.libfund.ru

  - name: Рука помощи43
    type: вк mcs0766305908
    url: mks.helpinghand43.ru

  - name: новое начало
    type: вк mcs0446143667
    url: xn--j1adq.xn--80aaem6ahcfbf0h.xn--p1ai

  - name: АНО Эпоха Водолея
    type: вк mcs7972760649
    url: mks.iznanka.info

  - name: ТЫ ДОМА
    type: вк mcs7451084416
    url: mks.td-samara.ru

  - name: Жить вместе
    type: вк mcs3416615957
    url: mks.zhitvmeste.ru

  - name: перспективы
    type: яндекс b1g45lnsetvmech979bb
    url: mks.perspektivy.ru

  - name: маяк
    type: яндекс b1gjlq3h33jrubagi0sp
    url: mks.stophomelessness.ru

  - name: Анна Помогает
    type: яндекс b1gn175pje1bs9a6lkdi
    url: mks.annapomogaet.ru

texts:
  messages:
    start: |
      {name}, привет! 🎉 Выбери необходимое действие в меню ✨
    status: |
      {name}, выбери тип статуса
    help: |
      /start - начальный экран
      /status - показать статус
      /help - показать подсказку
    permission_error: |
      Сорри, мы не знаем, кто ты. Напиши @kvendingoldo чтобы получить доступ к боту.
    processing: |
      Обрабатываю запрос, статус будет через несколько секунд ...
    wrong_msg: |
      Похоже что-то пошло не так. Пожалуйста, воспользуйся подсказкой через /help или начните заново через /start

colors:
  green: "#B6FFCE"
  yellow: "#F6FFA4"
  red: "#FFA8A8"
